# Docker compose config file

version: '3.8'

services:

  # service 1: api
  namaztime-api:
    image: golang:1.25-alpine3.22
    env_file:
      - .env  # файл с переменными окружения
    working_dir: /api
    volumes:
      - ./api:/api
    command: >
      /bin/sh -c "apk add --no-cache bash git && go mod download && go build -o namaztime-api . && ./namaztime-api"
    ports:
      - "8080:8080" # проброс порта
    # expose:
    #   - "8080"
    restart: unless-stopped

  # service 2: bot
  namaztime-bot:
    image: golang:1.25-alpine3.22
    env_file:
      - .envя
    working_dir: /bot
    volumes:
      - ./bot:/bot
    command: /bin/sh -c "apk add --no-cache bash git && go mod download && go build -o namaztime-bot . && ./namaztime-bot"
    depends_on:
      - namaztime-api # зависимость от namaztime-api
    restart: unless-stopped

  # # service 3: nginx
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"  # проброс порта 80 на хост
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # мой конфиг nginx
  #   depends_on:
  #     - namaztime-api
  #   restart: unless-stopped
  