# dockerfile from api: multi-stage build

# stage 1: build
from golang:1.25-bookworm as builder
workdir /bot
copy . .

# env http_proxy=http://user:password@ip:port
# env https_proxy=http://user:password@ip:port


# run go build -mod=vendor -o namaztime-bot .
run go build -mod=vendor -o namaztime-bot .

# stage 2: runtime
from debian:bookworm

# env http_proxy=http://user:password@ip:port
# env https_proxy=http://user:password@ip:port

run apt-get update && \
    apt-get install -y ca-certificates tzdata && \
    update-ca-certificates && \
    ln -sf /usr/share/zoneinfo/Asia/Krasnoyarsk /etc/localtime && \
    echo "Asia/Krasnoyarsk" > /etc/timezone

#ENV TZ=Asia/Krasnoyarsk

workdir /bot
copy --from=builder /bot/namaztime-bot .
cmd ["./namaztime-bot"]